[package]
name = "git-mirror"
version = "0.13.1"
authors = ["Pascal Bach <pascal.bach@nextrem.ch>"]
description = "Sync between different git repositories."
license = "MIT"
repository = "https://github.com/bachp/git-mirror"
keywords = ["git", "mirror", "sync"]
edition = "2018"

[features]

[dependencies]
chrono = "0.4"
log = "0.4"
env_logger = "0.7"
slug = "0.1"
rayon = "1.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
fs2 = "0.4"
prometheus = "0.7"
reqwest = "0.9"
openssl-probe = "0.1"
junit-report = "0.2"
structopt = "0.3"

[profile.release]
lto = true
