[package]
name = "git-mirror"
version = "0.6.0"
authors = ["Pascal Bach <pascal.bach@nextrem.ch>"]

[features]
native-tls = [ "hyper-native-tls" ]

[dependencies]
clap = "2.29.2"
chrono = "0.4.0"
log = "0.4.1"
stderrlog = "0.2.3"
slug = "0.1.2"
threadpool = "1.7.1"
hyper = "0.10.13"
hyper-native-tls = { version = "0.2.4", optional = true }
hyper-rustls = "0.6.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7.3"
fs2 = "0.4.3"
prometheus = "0.3.10"
